name: chatbot_multiatendimento
description: "Um projeto Flutter completo e otimizado."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ícones e UI
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0  # Animações suaves e fáceis

  # Gerenciamento de Estado
  get: ^4.6.6  # GetX para gerenciamento de estado e rotas
  provider: ^6.1.0  # Alternativa para gerenciamento de estado

  # Animações e UI avançada
  animations: ^2.0.7
  lottie: ^2.7.0  # Animações JSON do After Effects

  # Gráficos e Indicadores
  fl_chart: ^0.70.2  # Gráficos avançados
  percent_indicator: ^4.2.3  # Indicadores de progresso

  # Rede e APIs
  dio: ^5.4.1  # Cliente HTTP poderoso
  http: ^1.2.0  # Alternativa ao Dio para chamadas REST

  # Firebase (caso precise)
  firebase_core: ^2.30.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.17.0

  # Armazenamento local
  shared_preferences: ^2.2.2  # Armazena preferências do usuário
  hive: ^2.2.3  # Banco de dados local rápido
  hive_flutter: ^1.1.0

  # Notificações e Permissões
  flutter_local_notifications: ^16.3.2
  permission_handler: ^11.3.1

  # Outras ferramentas úteis
  intl: ^0.19.0  # Manipulação de datas e números
  path_provider: ^2.1.2  # Acesso a diretórios locais
  url_launcher: ^6.2.5  # Abrir URLs e links externos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
